/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ncp.airlock.client.model.Experiment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents the existing Airlock experiments list.
 */
@ApiModel(description = "Represents the existing Airlock experiments list.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-10-26T06:00:40.553Z[Etc/UTC]")
public class ExperimentList {
  public static final String SERIALIZED_NAME_EXPERIMENTS = "experiments";
  @SerializedName(SERIALIZED_NAME_EXPERIMENTS)
  private List<Experiment> experiments = null;

  public ExperimentList experiments(List<Experiment> experiments) {
    this.experiments = experiments;
    return this;
  }

  public ExperimentList addExperimentsItem(Experiment experimentsItem) {
    if (this.experiments == null) {
      this.experiments = new ArrayList<>();
    }
    this.experiments.add(experimentsItem);
    return this;
  }

   /**
   * List of experiments.
   * @return experiments
  **/
  @ApiModelProperty(value = "List of experiments.")
  public List<Experiment> getExperiments() {
    return experiments;
  }

  public void setExperiments(List<Experiment> experiments) {
    this.experiments = experiments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentList experimentList = (ExperimentList) o;
    return Objects.equals(this.experiments, experimentList.experiments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(experiments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentList {\n");
    
    sb.append("    experiments: ").append(toIndentedString(experiments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

