/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ncp.airlock.client.model.Attribute;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * An object containing all analytics related data for a specific feature.
 */
@ApiModel(description = "An object containing all analytics related data for a specific feature.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-11-27T09:43:16.328Z[Etc/UTC]")
public class FeatureAnalytics {
  public static final String SERIALIZED_NAME_FEATURE_NAME = "featureName";
  @SerializedName(SERIALIZED_NAME_FEATURE_NAME)
  private String featureName = null;

  public static final String SERIALIZED_NAME_SEND_ON = "sendOn";
  @SerializedName(SERIALIZED_NAME_SEND_ON)
  private Boolean sendOn = null;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private List<Attribute> attributes = null;

  public static final String SERIALIZED_NAME_APPLIED_CONFIGURATION_RULES = "appliedConfigurationRules";
  @SerializedName(SERIALIZED_NAME_APPLIED_CONFIGURATION_RULES)
  private List<String> appliedConfigurationRules = null;

  public static final String SERIALIZED_NAME_APPLIED_ORDERING_RULES = "appliedOrderingRules";
  @SerializedName(SERIALIZED_NAME_APPLIED_ORDERING_RULES)
  private List<String> appliedOrderingRules = null;

  public static final String SERIALIZED_NAME_ORDERED_CHILDREN = "orderedChildren";
  @SerializedName(SERIALIZED_NAME_ORDERED_CHILDREN)
  private List<String> orderedChildren = null;

  public FeatureAnalytics featureName(String featureName) {
    this.featureName = featureName;
    return this;
  }

   /**
   * The feature name.
   * @return featureName
  **/
  @ApiModelProperty(value = "The feature name.")
  public String getFeatureName() {
    return featureName;
  }

  public void setFeatureName(String featureName) {
    this.featureName = featureName;
  }

  public FeatureAnalytics sendOn(Boolean sendOn) {
    this.sendOn = sendOn;
    return this;
  }

   /**
   * Indicating if the feature should be reported to analytics.
   * @return sendOn
  **/
  @ApiModelProperty(value = "Indicating if the feature should be reported to analytics.")
  public Boolean isSendOn() {
    return sendOn;
  }

  public void setSendOn(Boolean sendOn) {
    this.sendOn = sendOn;
  }

  public FeatureAnalytics attributes(List<Attribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public FeatureAnalytics addAttributesItem(Attribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * The configuration attributes (key/value pairs) that were set to be reported to analytics.
   * @return attributes
  **/
  @ApiModelProperty(value = "The configuration attributes (key/value pairs) that were set to be reported to analytics.")
  public List<Attribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<Attribute> attributes) {
    this.attributes = attributes;
  }

  public FeatureAnalytics appliedConfigurationRules(List<String> appliedConfigurationRules) {
    this.appliedConfigurationRules = appliedConfigurationRules;
    return this;
  }

  public FeatureAnalytics addAppliedConfigurationRulesItem(String appliedConfigurationRulesItem) {
    if (this.appliedConfigurationRules == null) {
      this.appliedConfigurationRules = new ArrayList<>();
    }
    this.appliedConfigurationRules.add(appliedConfigurationRulesItem);
    return this;
  }

   /**
   * An array containing the configuration rules that were both applied and marked to be reported to analytics.
   * @return appliedConfigurationRules
  **/
  @ApiModelProperty(value = "An array containing the configuration rules that were both applied and marked to be reported to analytics.")
  public List<String> getAppliedConfigurationRules() {
    return appliedConfigurationRules;
  }

  public void setAppliedConfigurationRules(List<String> appliedConfigurationRules) {
    this.appliedConfigurationRules = appliedConfigurationRules;
  }

  public FeatureAnalytics appliedOrderingRules(List<String> appliedOrderingRules) {
    this.appliedOrderingRules = appliedOrderingRules;
    return this;
  }

  public FeatureAnalytics addAppliedOrderingRulesItem(String appliedOrderingRulesItem) {
    if (this.appliedOrderingRules == null) {
      this.appliedOrderingRules = new ArrayList<>();
    }
    this.appliedOrderingRules.add(appliedOrderingRulesItem);
    return this;
  }

   /**
   * An array containing the ordering rules that were both applied and marked to be reported to analytics.
   * @return appliedOrderingRules
  **/
  @ApiModelProperty(value = "An array containing the ordering rules that were both applied and marked to be reported to analytics.")
  public List<String> getAppliedOrderingRules() {
    return appliedOrderingRules;
  }

  public void setAppliedOrderingRules(List<String> appliedOrderingRules) {
    this.appliedOrderingRules = appliedOrderingRules;
  }

  public FeatureAnalytics orderedChildren(List<String> orderedChildren) {
    this.orderedChildren = orderedChildren;
    return this;
  }

  public FeatureAnalytics addOrderedChildrenItem(String orderedChildrenItem) {
    if (this.orderedChildren == null) {
      this.orderedChildren = new ArrayList<>();
    }
    this.orderedChildren.add(orderedChildrenItem);
    return this;
  }

   /**
   * An array containing the names of the children according their order based on the last calculation.
   * @return orderedChildren
  **/
  @ApiModelProperty(value = "An array containing the names of the children according their order based on the last calculation.")
  public List<String> getOrderedChildren() {
    return orderedChildren;
  }

  public void setOrderedChildren(List<String> orderedChildren) {
    this.orderedChildren = orderedChildren;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureAnalytics featureAnalytics = (FeatureAnalytics) o;
    return Objects.equals(this.featureName, featureAnalytics.featureName) &&
        Objects.equals(this.sendOn, featureAnalytics.sendOn) &&
        Objects.equals(this.attributes, featureAnalytics.attributes) &&
        Objects.equals(this.appliedConfigurationRules, featureAnalytics.appliedConfigurationRules) &&
        Objects.equals(this.appliedOrderingRules, featureAnalytics.appliedOrderingRules) &&
        Objects.equals(this.orderedChildren, featureAnalytics.orderedChildren);
  }

  @Override
  public int hashCode() {
    return Objects.hash(featureName, sendOn, attributes, appliedConfigurationRules, appliedOrderingRules, orderedChildren);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureAnalytics {\n");
    
    sb.append("    featureName: ").append(toIndentedString(featureName)).append("\n");
    sb.append("    sendOn: ").append(toIndentedString(sendOn)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    appliedConfigurationRules: ").append(toIndentedString(appliedConfigurationRules)).append("\n");
    sb.append("    appliedOrderingRules: ").append(toIndentedString(appliedOrderingRules)).append("\n");
    sb.append("    orderedChildren: ").append(toIndentedString(orderedChildren)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

