/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ncp.airlock.client.model.Feature;
import com.ncp.airlock.client.model.FeatureDebugInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Represents an Airlock feature.
 */
@ApiModel(description = "Represents an Airlock feature.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-11-27T09:43:16.328Z[Etc/UTC]")
public class Feature {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = null;

  public static final String SERIALIZED_NAME_ON = "on";
  @SerializedName(SERIALIZED_NAME_ON)
  private Boolean on = null;

  public static final String SERIALIZED_NAME_CONFIGURATION = "configuration";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION)
  private Map<String, Object> _configuration = null;

  public static final String SERIALIZED_NAME_CHILDREN = "children";
  @SerializedName(SERIALIZED_NAME_CHILDREN)
  private List<Feature> children = null;

  public static final String SERIALIZED_NAME_PARENT_NAME = "parentName";
  @SerializedName(SERIALIZED_NAME_PARENT_NAME)
  private String parentName = null;

  public static final String SERIALIZED_NAME_DEBUG_INFO = "debugInfo";
  @SerializedName(SERIALIZED_NAME_DEBUG_INFO)
  private FeatureDebugInfo debugInfo = null;

  public Feature name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Feature name.
   * @return name
  **/
  @ApiModelProperty(value = "Feature name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Feature on(Boolean on) {
    this.on = on;
    return this;
  }

   /**
   * Indicates whether the feature is ON/OFF based on the last calculation.
   * @return on
  **/
  @ApiModelProperty(value = "Indicates whether the feature is ON/OFF based on the last calculation.")
  public Boolean isOn() {
    return on;
  }

  public void setOn(Boolean on) {
    this.on = on;
  }

  public Feature _configuration(Map<String, Object> _configuration) {
    this._configuration = _configuration;
    return this;
  }

  public Feature putConfigurationItem(String key, Object _configurationItem) {
    if (this._configuration == null) {
      this._configuration = new HashMap<>();
    }
    this._configuration.put(key, _configurationItem);
    return this;
  }

   /**
   * The configuration object for this feature.
   * @return _configuration
  **/
  @ApiModelProperty(value = "The configuration object for this feature.")
  public Map<String, Object> getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(Map<String, Object> _configuration) {
    this._configuration = _configuration;
  }

  public Feature children(List<Feature> children) {
    this.children = children;
    return this;
  }

  public Feature addChildrenItem(Feature childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Features children.
   * @return children
  **/
  @ApiModelProperty(value = "Features children.")
  public List<Feature> getChildren() {
    return children;
  }

  public void setChildren(List<Feature> children) {
    this.children = children;
  }

  public Feature parentName(String parentName) {
    this.parentName = parentName;
    return this;
  }

   /**
   * Feature parent name.
   * @return parentName
  **/
  @ApiModelProperty(value = "Feature parent name.")
  public String getParentName() {
    return parentName;
  }

  public void setParentName(String parentName) {
    this.parentName = parentName;
  }

  public Feature debugInfo(FeatureDebugInfo debugInfo) {
    this.debugInfo = debugInfo;
    return this;
  }

   /**
   * Get debugInfo
   * @return debugInfo
  **/
  @ApiModelProperty(value = "")
  public FeatureDebugInfo getDebugInfo() {
    return debugInfo;
  }

  public void setDebugInfo(FeatureDebugInfo debugInfo) {
    this.debugInfo = debugInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Feature feature = (Feature) o;
    return Objects.equals(this.name, feature.name) &&
        Objects.equals(this.on, feature.on) &&
        Objects.equals(this._configuration, feature._configuration) &&
        Objects.equals(this.children, feature.children) &&
        Objects.equals(this.parentName, feature.parentName) &&
        Objects.equals(this.debugInfo, feature.debugInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, on, _configuration, children, parentName, debugInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Feature {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    on: ").append(toIndentedString(on)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    parentName: ").append(toIndentedString(parentName)).append("\n");
    sb.append("    debugInfo: ").append(toIndentedString(debugInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

