/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents an Airlock product registered on the SDK.
 */
@ApiModel(description = "Represents an Airlock product registered on the SDK.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2018-11-27T09:43:16.328Z[Etc/UTC]")
public class Product {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = null;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private String productId = null;

  public static final String SERIALIZED_NAME_SEASON_ID = "seasonId";
  @SerializedName(SERIALIZED_NAME_SEASON_ID)
  private String seasonId = null;

  public static final String SERIALIZED_NAME_APP_VERSION = "appVersion";
  @SerializedName(SERIALIZED_NAME_APP_VERSION)
  private String appVersion = null;

  public static final String SERIALIZED_NAME_INSTANCE_ID = "instanceId";
  @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
  private String instanceId = null;

  public Product name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Product name.
   * @return name
  **/
  @ApiModelProperty(value = "Product name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Product productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Product id.
   * @return productId
  **/
  @ApiModelProperty(value = "Product id.")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public Product seasonId(String seasonId) {
    this.seasonId = seasonId;
    return this;
  }

   /**
   * The season of the application associated with this product as it was provided during initialization.
   * @return seasonId
  **/
  @ApiModelProperty(value = "The season of the application associated with this product as it was provided during initialization.")
  public String getSeasonId() {
    return seasonId;
  }

  public void setSeasonId(String seasonId) {
    this.seasonId = seasonId;
  }

  public Product appVersion(String appVersion) {
    this.appVersion = appVersion;
    return this;
  }

   /**
   * The version of the application associated with this product as it was provided during initialization.
   * @return appVersion
  **/
  @ApiModelProperty(value = "The version of the application associated with this product as it was provided during initialization.")
  public String getAppVersion() {
    return appVersion;
  }

  public void setAppVersion(String appVersion) {
    this.appVersion = appVersion;
  }

  public Product instanceId(String instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * The instanceId of this product as it was provided during initialization.
   * @return instanceId
  **/
  @ApiModelProperty(value = "The instanceId of this product as it was provided during initialization.")
  public String getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.name, product.name) &&
        Objects.equals(this.productId, product.productId) &&
        Objects.equals(this.seasonId, product.seasonId) &&
        Objects.equals(this.appVersion, product.appVersion) &&
        Objects.equals(this.instanceId, product.instanceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, productId, seasonId, appVersion, instanceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    seasonId: ").append(toIndentedString(seasonId)).append("\n");
    sb.append("    appVersion: ").append(toIndentedString(appVersion)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

