/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client;

import com.ncp.airlock.client.invoker.ApiException;
import com.ncp.airlock.client.model.AnalyticsData;
import com.ncp.airlock.client.model.FeatureAnalytics;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnalyticsApi
 */
@Ignore
public class AnalyticsApiTest {

    private final AnalyticsApi api = new AnalyticsApi();

    
    /**
     * Retrieves all analytics data marked to be sent in the Control Center including context fields and feature information.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllFieldsForAnalyticsTest() throws ApiException {
        String productInstanceId = null;
        AnalyticsData response = api.getAllFieldsForAnalytics(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Retrieves all analytics data marked to be sent in the Control Center for the specified feature.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFeatureAttributesForAnalyticsTest() throws ApiException {
        String productInstanceId = null;
        String featureName = null;
        FeatureAnalytics response = api.getFeatureAttributesForAnalytics(productInstanceId, featureName);

        // TODO: test validations
    }
    
}
