/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client;

import com.ncp.airlock.client.invoker.ApiException;
import com.ncp.airlock.client.model.Feature;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FeaturesApi
 */
@Ignore
public class FeaturesApiTest {

    private final FeaturesApi api = new FeaturesApi();

    
    /**
     * Retrieves the feature with the specified name.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFeatureByNameTest() throws ApiException {
        String productInstanceId = null;
        String featureName = null;
        Feature response = api.getFeatureByName(productInstanceId, featureName);

        // TODO: test validations
    }
    
    /**
     * Retrieves the children of the specified feature.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFeatureChildrenTest() throws ApiException {
        String productInstanceId = null;
        String featureName = null;
        List<Feature> response = api.getFeatureChildren(productInstanceId, featureName);

        // TODO: test validations
    }
    
}
