/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client;

import com.ncp.airlock.client.invoker.ApiException;
import com.ncp.airlock.client.model.Product;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Ignore
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    
    /**
     * Removes the specified product completely from the system including all cached data related to it. Parallel to uninstalling the application.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        String productInstanceId = null;
        String response = api.delete(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Retrieves all products.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllProductsTest() throws ApiException {
        List<Product> response = api.getAllProducts();

        // TODO: test validations
    }
    
    /**
     * Retrieves a product by its id.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductByIDTest() throws ApiException {
        String productInstanceId = null;
        Product response = api.getProductByID(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Initializes a product in Airlock. Must be called once before any other Airlock function can be used in this product. In case the product is already initialized and the product&#39;s version or defaults file does not match the previously initialized product then all of the product&#39;s cached data will be cleared except for user groups. Otherwise, this operation will have no affect.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void initTest() throws ApiException {
        String appVersion = null;
        Object UNKNOWN_BASE_TYPE = null;
        String encryptionKey = null;
        Product response = api.init(appVersion, UNKNOWN_BASE_TYPE, encryptionKey);

        // TODO: test validations
    }
    
}
