/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client;

import com.ncp.airlock.client.invoker.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StreamsApi
 */
@Ignore
public class StreamsApiTest {

    private final StreamsApi api = new StreamsApi();

    
    /**
     * Add events to the streams processing stack
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addEventsTest() throws ApiException {
        String productInstanceId = null;
        List<Object> ERROR_UNKNOWN = null;
        String response = api.addEvents(productInstanceId, ERROR_UNKNOWN);

        // TODO: test validations
    }
    
    /**
     * Retrieves the last streams calculation results
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStreamsResultsTest() throws ApiException {
        String productInstanceId = null;
        Map<String, Object> response = api.getStreamsResults(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Calculates all streams according to the events sent
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runStreamsTest() throws ApiException {
        String productInstanceId = null;
        String streamId = null;
        List<Object> ERROR_UNKNOWN = null;
        String response = api.runStreams(productInstanceId, streamId, ERROR_UNKNOWN);

        // TODO: test validations
    }
    
}
