/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client;

import com.ncp.airlock.client.invoker.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StringsApi
 */
@Ignore
public class StringsApiTest {

    private final StringsApi api = new StringsApi();

    
    /**
     * Retrieves all strings translated based on the locale of the application as specified in the pull function. Placeholders will not be replaced with any values and will be returned in their original form.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllStringsTest() throws ApiException {
        String productInstanceId = null;
        Map<String, Object> response = api.getAllStrings(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Retrieves the translated string with the specified key based on the locale of the application as specified in the pull function.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStringByKeyTest() throws ApiException {
        String productInstanceId = null;
        String key = null;
        List<String> ERROR_UNKNOWN = null;
        String response = api.getStringByKey(productInstanceId, key, ERROR_UNKNOWN);

        // TODO: test validations
    }
    
}
