/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ncp.airlock.client;

import com.ncp.airlock.client.invoker.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserGroupsApi
 */
@Ignore
public class UserGroupsApiTest {

    private final UserGroupsApi api = new UserGroupsApi();

    
    /**
     * Retrieves all user groups exists for the specified product on the server.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserGroupsTest() throws ApiException {
        String productInstanceId = null;
        List<Object> response = api.getAllUserGroups(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Retrieves all user groups that were set for the specified product.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserGroupsTest() throws ApiException {
        String productInstanceId = null;
        List<Object> response = api.getUserGroups(productInstanceId);

        // TODO: test validations
    }
    
    /**
     * Updates the list of user groups for the specified product with the specified list. All previously set user groups will be overridden with this list, unless the product has the same user groups list.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserGroupsToProductTest() throws ApiException {
        String productInstanceId = null;
        List<String> ERROR_UNKNOWN = null;
        String response = api.updateUserGroupsToProduct(productInstanceId, ERROR_UNKNOWN);

        // TODO: test validations
    }
    
}
